version: '2'
services:
    web:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./content/web/:/var/www/web/
        links:
            - redis
            - db
        stdin_open: true
        tty: true
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: dev
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: myapp